### ISSUE TITLE
I write slow code

### ISSUE THREAD

**Issue by noxecane** [darthchudi/danfo#4]
## Issues
- there's no prefetch for consumers
- I don't have control over how I consume(I can't control the number of goroutines running).
- This might seem harsh but the strategy of one goroutine per message might become problematic when there's a large number of messages being sent and the task itself is long-running(redundant complaint anyways)

Most of these complaints stem from the fact that the API uses a callback.

**Comment by darthchudi** [comment]
Noted. 

- Prefetch will be added as an optional parameter to the `subscriber.Consume()` and `subscriber.On` consumer methods.
- Re: goroutines; I agree, returning the deliveries `channel` frees Danfo from having to decide the concurrency pattern(s) for consuming messages and returns control to the caller. It will be addressed in the next couple of PRs 😅
